version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: RANCHER API URL
          command: |
            echo 'export FULL_RANCHER_WORKLOAD_REDEPLOYMENT_API="https://${TARGET_SERVER_ADDRESSS}:8443${RANCHER_WORKLOAD_REDEPLOYMENT_API}"' >> $BASH_ENV
          
      - run:
          name: FULL_RANCHER_WORKLOAD_REDEPLOYMENT_API
          command: echo ${FULL_RANCHER_WORKLOAD_REDEPLOYMENT_API}
          
      # - run:
      #     name: RANCHER API DATA
      #     command: echo ${}