version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: RANCHER API URL
          command: echo ${RANCHER_WORKLOAD_REDEPLOYMENT_API}

      # - run:
      #     name: RANCHER API DATA
      #     command: echo ${}